---
- name: Test SSH, create user lab, and copy SSH public key
  hosts: lab_clients
  become: yes
  become_method: sudo
  become_user: root
  gather_facts: false
  vars:
    #ansible_user: admin-linux
    #ansible_password: !
    lab_password_hash: "$6$P/hwM02g8hFlKdYo$N3F1.KwlS0Jiihykn88Qs549DDR3lkKuM7krwN4zvH7km5id8eC3U0mjvxMIboa3B1IMZ6RGxB2ENIuFPihmM0"
    lab_ssh_public_key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIHuYJV1wUnRkV+vtFaH7qbCb/xJbaAIxhqWIli/3bUzr Semaphore@LULC-ANSI-SRV"

  tasks:
    - name: Test SSH connectivity
      ansible.builtin.ping:
      register: ping_result
      failed_when: ping_result.failed

    - name: Display SSH connection result
      ansible.builtin.debug:
        msg: "SSH connection to {{ inventory_hostname }} as {{ ansible_user }}: {{ ping_result.ping }}"
      when: ping_result.ping == 'pong'

    - name: Create user lab
      ansible.builtin.user:
        name: lab
        password: "{{ lab_password_hash }}"
        shell: /bin/bash
        state: present
      when: ping_result.ping == 'pong'

    - name: Ensure SSH directory exists for lab
      ansible.builtin.file:
        path: /home/lab/.ssh
        state: directory
        owner: lab
        group: lab
        mode: "0700"
      when: ping_result.ping == 'pong'

    #- name: Copy SSH public key to lab's authorized_keys
    #  ansible.posix.authorized_key:
    #    user: lab
    #    key: "{{ lab_ssh_public_key }}"
    #    state: present
    #  when: ping_result.ping == 'pong'
