---
- hosts: test
  become: true
  tasks:
    - name: Copy the new_users script
      ansible.builtin.copy:
        src: new_users.sh # Make sure this path is correct!
        dest: /tmp/semaphore/project_1/repository_1_template_2/new_users.sh
        mode: '0755'

    - name: Copy the users CSV file
      ansible.builtin.copy:
        src: users.csv
        dest: /tmp/semaphore/project_1/repository_1_template_2/users.csv
        mode: '0755'

    # --- ADD THIS DEBUG BLOCK ---
    - name: DEBUG - Show the script that was copied to the remote server
      ansible.builtin.command:
        cmd: cat /tmp/semaphore/project_1/repository_1_template_2/new_users.sh
      register: script_contents

    - name: DEBUG - Print the script contents for verification
      ansible.builtin.debug:
        var: script_contents.stdout_lines
    # --- END DEBUG BLOCK ---

    - name: Execute the script
      ansible.builtin.shell:
        cmd: ./new_users.sh users.csv
        chdir: /tmp/semaphore/project_1/repository_1_template_2
