---
- hosts: test
  become: true
  tasks:
    - name: Get current working directory
      ansible.builtin.shell: pwd
      register: current_working_directory

    - name: Display current working directory
      debug:
       msg: "The current working directory is: {{ current_working_directory.stdout }}"
    
    - name: Get current files in directory
      ansible.builtin.shell: ls -la
      register: files_list

    - name: Display files in current working directory
      debug:
       msg: "The current working directory is: {{ files_list.stdout }}"

    - name: Execute the script
      ansible.builtin.shell:
        cmd: ./users.sh users.csv
        chdir: /tmp/semaphore/project_1/repository_1_template_2
