---
- hosts: test
  become: true
  tasks:
    - name: Get current working directory
      ansible.builtin.shell: pwd
      register: current_working_directory

    - name: Display current working directory
      debug:
       msg: "The current working directory is: {{ current_working_directory.stdout }}"
    
    - name: Get current files in directory
      ansible.builtin.shell: ls -l
      register: files_list

    - name: Copy the new_users script
      ansible.builtin.copy:
        src: users.sh users.csv
        dest: /tmp/semaphore/project_1/repository_1_template_2/users.sh
        mode: '0755'

    - name: Execute the script
      ansible.builtin.shell:
        cmd: ./users.sh users.csv
        chdir: /tmp/semaphore/project_1/repository_1_template_2
