---
- hosts: test
  become: true
  tasks:
    - name: Get current working directory
      ansible.builtin.shell: pwd
      register: current_working_directory

    - name: Display current working directory
      debug:
       msg: "The current working directory is: {{ current_working_directory.stdout }}"

    - name: Find files you want to copy
      ansible.builtin.find:
        paths: .
        file_type: file
      register: files_output

    - name: Copy the files
      ansible.builtin.copy:
        src: "{{ item.path }}"
        dest: /tmp/semaphore/project_1/repository_1_template_2/
      loop: "{{ files_output.files }}"

    - name: Execute the script
      ansible.builtin.shell:
        cmd: ./users.sh users.csv
        chdir: /tmp/semaphore/project_1/repository_1_template_2
