---
- hosts: test
  become: true
  tasks:
    - name: Get current working directory
      ansible.builtin.shell: pwd
      register: current_working_directory

    - name: Display current working directory
      debug:
       msg: "The current working directory is: {{ current_working_directory.stdout }}"

    - name: Copying files
      ansible.builtin.copy:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
      loop:
        - src: users.sh
        - dest: /tmp/semaphore/project_1/repository_1_template_2
        - src: users.csv
        - dest: /tmp/semaphore/project_1/repository_1_template_2
        - src: lu.yaml
        - dest: /tmp/semaphore/project_1/repository_1_template_2

    - name: Execute the script
      ansible.builtin.shell:
        cmd: ./users.sh users.csv
        chdir: /tmp/semaphore/project_1/repository_1_template_2
