---
- hosts: test
  become: true
  tasks:
    - name: Execute the script
      ansible.builtin.shell:
        cmd: ./users.sh users.csv
        chdir: /tmp/semaphore/project_1/repository_1_template_2
