---
- hosts: lu_lab
  become: true
  tasks:
    - name: Create a directory if it does not exist
      ansible.builtin.file:
        path: /tmp/semaphore/project_1/repository_1_template_2
        state: directory
        mode: '0755'

    - name: Copy the new_users script to the remote server
      ansible.builtin.copy:
        src: new_users.sh
        dest: /tmp/semaphore/project_1/repository_1_template_2/new_users.sh
        mode: '0755'

    - name: Copy the users CSV file to the remote server
      # FIX 1: Add this task to copy the required CSV file.
      ansible.builtin.copy:
        src: users.csv   # Assumes users.csv is in the same folder as your playbook
        dest: /tmp/semaphore/project_1/repository_1_template_2/users.csv

    - name: Execute the script with the CSV file as an argument
      ansible.builtin.shell:
        # FIX 2: Add the CSV filename after the script name.
        cmd: ./new_users.sh users.csv
        # Change to the script's directory before running
        chdir: /tmp/semaphore/project_1/repository_1_template_2
